global:
  scrape_interval: 7s

scrape_configs:
  - job_name: 'My app'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    basic_auth:
      username: 'bob@gmail.com'
      password: 'passBob'
      
